# Generated by Django 4.1.4 on 2023-01-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachersAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['email'], 'verbose_name': 'Nastavnik', 'verbose_name_plural': 'Nastavnici'},
        ),
        migrations.AddField(
            model_name='teacher',
            name='canton',
            field=models.CharField(default='ZDK', max_length=3),
        ),
    ]
