# Generated by Django 4.1.4 on 2023-01-06 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachersAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='canton_code',
            field=models.ForeignKey(default='ZDK', on_delete=django.db.models.deletion.CASCADE, to='teachersAuth.canton'),
        ),
    ]
