# Generated by Django 4.1.4 on 2023-05-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachersAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
