# Generated by Django 4.1.4 on 2023-01-06 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachersAuth', '0002_alter_teacher_canton_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimarySchools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ps_name', models.CharField(default='Tehnicka skola Zenica', max_length=100, unique=True)),
                ('ps_address', models.CharField(default='Bilimisce 28, Zenica', max_length=100)),
            ],
            options={
                'db_table': 'primarySchools',
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='ps_id',
            field=models.ForeignKey(default='Tehnicka skola Zenica', on_delete=django.db.models.deletion.CASCADE, to='teachersAuth.primaryschools', to_field='ps_name'),
        ),
    ]
