# Generated by Django 4.1.4 on 2023-01-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachersAuth', '0002_alter_teacher_options_teacher_canton'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(fields=('id', 'email'), name='composite-pk-id-email'),
        ),
    ]
