# Generated by Django 4.1.4 on 2023-01-06 11:26

from django.db import migrations
import teachersAuth.models


class Migration(migrations.Migration):

    dependencies = [
        ('teachersAuth', '0003_primaryschools_teacher_ps_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='teacher',
            managers=[
                ('objects', teachersAuth.models.CustomUserManager()),
            ],
        ),
    ]
