# Generated by Django 4.1.4 on 2023-01-09 22:52

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('_canton_code', models.CharField(default='ZDK', max_length=3, primary_key=True, serialize=False)),
                ('canton_name', models.CharField(default='Zenicko-dobojski', max_length=50)),
                ('country', django_countries.fields.CountryField(default='BA', max_length=2)),
            ],
            options={
                'db_table': 'cantons',
            },
        ),
        migrations.CreateModel(
            name='SecondarySchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Tehnicka skola Zenica', max_length=100, unique=True)),
                ('school_address', models.CharField(default='Bilimisce 28, Zenica', max_length=100)),
                ('school_canton_code', models.ForeignKey(default='ZDK', on_delete=django.db.models.deletion.CASCADE, related_name='school_canton', to='secondarySchools.canton')),
            ],
            options={
                'db_table': 'secondarySchools',
            },
        ),
        migrations.CreateModel(
            name='CoursesSecondarySchool',
            fields=[
                ('_course_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('course_duration', models.CharField(choices=[('III', 'Trogodisnje'), ('IV', 'Cetverogodisnje')], default='IV', max_length=10)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_secondary', to='secondarySchools.secondaryschool')),
            ],
            options={
                'db_table': 'courses_secondary',
            },
        ),
        migrations.AddConstraint(
            model_name='coursessecondaryschool',
            constraint=models.UniqueConstraint(fields=('school_id', '_course_code'), name='composite-pk-school_id-course_code'),
        ),
    ]
