# Generated by Django 4.1.4 on 2023-05-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondarySchools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondaryschool',
            name='school_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
