# Generated by Django 4.1.4 on 2023-05-27 11:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secondarySchools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ack_name', models.CharField(max_length=100)),
                ('ack_points', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'acknowledgments',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('_classes', models.CharField(choices=[('I', '1'), ('II', '2'), ('III', '3'), ('IV', '4'), ('V', '5'), ('VI', '6'), ('VII', '7'), ('VIII', '8'), ('IX', '9')], max_length=5, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'studentClass',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_code', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('course_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_school', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=60)),
                ('guardian_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+<387xxxxxxx>'. Up to 12 digits allowed.", regex='^\\+?1?\\d{9,12}$')])),
                ('guardian_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+<387xxxxxxx>'. Up to 12 digits allowed.", regex='^\\+?1?\\d{9,12}$')])),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_enrollment', models.DateField(auto_now_add=True)),
                ('special_case', models.CharField(choices=[('regular', 'Regular student'), ('invalid', 'Invaliditet'), ('others', 'Ostali')], default='regular', max_length=10)),
                ('acknowledgment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_acknowledgment', to='student.acknowledgment')),
                ('desired_course_A', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_secondary_school_desired_course_A', to='secondarySchools.coursessecondaryschool')),
                ('secondary_shool_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_secondary_school', to='secondarySchools.secondaryschool')),
            ],
            options={
                'db_table': 'pupils',
            },
        ),
        migrations.CreateModel(
            name='SpecialCoursesPerDesiredChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_course_course_code', to='secondarySchools.coursessecondaryschool')),
                ('primary_class_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_course_class_id', to='student.class')),
                ('primary_class_course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_course_class_course_code', to='student.courses')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_course_school_id', to='secondarySchools.secondaryschool')),
            ],
        ),
        migrations.CreateModel(
            name='PupilClassesCoursesGrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)])),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pupil_class_id', to='student.class')),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pupil_courses_code', to='student.courses')),
                ('pupil_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pupil_id', to='student.pupil')),
            ],
            options={
                'db_table': 'PupilClassesCoursesGrades',
            },
        ),
        migrations.AddConstraint(
            model_name='pupilclassescoursesgrades',
            constraint=models.UniqueConstraint(fields=('pupil_id', 'class_id', 'course_code'), name='composite-pk-pupil_id-class_id-course_code'),
        ),
        migrations.AddConstraint(
            model_name='pupil',
            constraint=models.UniqueConstraint(fields=('name', 'last_name', 'address'), name='composite-pk-name-last_name-address'),
        ),
    ]
