# Generated by Django 4.1.4 on 2023-05-24 13:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secondarySchools', '0002_secondaryschool_school_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ack_name', models.CharField(max_length=100)),
                ('ack_points', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'acknowledgments',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('_classes', models.CharField(choices=[('I', '1'), ('II', '2'), ('III', '3'), ('IV', '4'), ('V', '5'), ('VI', '6'), ('VII', '7'), ('VIII', '8'), ('IX', '9')], max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_school', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=60)),
                ('guardian_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+<387xxxxxxx>'. Up to 12 digits allowed.", regex='^\\+?1?\\d{9,12}$')])),
                ('guardian_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+<387xxxxxxx>'. Up to 12 digits allowed.", regex='^\\+?1?\\d{9,12}$')])),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('year_of_enrollment', models.DateField(auto_now_add=True)),
                ('special_case', models.CharField(choices=[('regular', 'Regular student'), ('invalid', 'Invaliditet'), ('others', 'Ostali')], default='regular', max_length=10)),
                ('acknowledgment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_acknowledgment', to='student.acknowledgment')),
                ('secondary_shool_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_secondary_school', to='secondarySchools.secondaryschool')),
            ],
            options={
                'db_table': 'pupil',
            },
        ),
        migrations.CreateModel(
            name='PupilClassesGrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)])),
                ('pupil_behavior', models.CharField(choices=[('5', 'odlican'), ('4', 'vrlo dobar'), ('3', 'dobar'), ('2', 'zadovoljava')], max_length=10)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pupil_classes', to='student.class')),
                ('pupil_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pupil_classes', to='student.pupil')),
            ],
            options={
                'db_table': 'pupilClasses',
            },
        ),
    ]
