# Generated by Django 4.1.4 on 2023-05-24 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='class',
            table='studentClass',
        ),
    ]
