# Generated by Django 4.1.4 on 2024-03-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='class_IX',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courses',
            name='class_VI',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courses',
            name='class_VII',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courses',
            name='class_VIII',
            field=models.BooleanField(default=False),
        ),
    ]
