# Generated by Django 4.1.4 on 2024-04-01 16:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_courses_class_ix_courses_class_vi_courses_class_vii_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PupilClassesAcknowledgments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ack_name', models.CharField(max_length=100)),
                ('ack_points', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ack_position', models.PositiveIntegerField(choices=[(1, 'Prvo mjesto'), (2, 'Drugo mjesto'), (3, 'Treće mjesto')])),
                ('ack_level', models.CharField(choices=[('Federalno', 'Federalno takmičenje'), ('Kantonalno', 'Kantonalno takmičenje'), ('Općinsko', 'Općinsko takmičenje')], max_length=20)),
                ('ack_class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pupil_ack_class_id', to='student.class')),
                ('pupil_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pupil_id_acknowledgments', to='student.pupil')),
            ],
            options={
                'db_table': 'PupilClassesAcknowledgments',
            },
        ),
        migrations.AddConstraint(
            model_name='pupilclassesacknowledgments',
            constraint=models.UniqueConstraint(fields=('pupil_id', 'ack_name', 'ack_level', 'ack_class_id'), name='composite-pk-pupil_id-ack_name-ack_level-ack_class_id'),
        ),
    ]
