# Generated by Django 4.1.4 on 2023-05-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_year_of_enrollment_pupil_date_of_enrollment'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pupil',
            constraint=models.UniqueConstraint(fields=('name', 'last_name', 'address'), name='composite-pk-name-last_name-address'),
        ),
        migrations.AlterModelTable(
            name='pupil',
            table='pupils',
        ),
    ]
