name: Django CI

on:
  # any code pushed to master and develop branch will be a trigger
  push:
    branches: [ "main", "develop", "learning-1"  ]
  # any code pushed to master and develop branch will also be a trigger
  pull_request:
    branches: [ "main"]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8.16]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        # I couldn't update packages here because of sudo
        # It is done manually, updated python3 and pip3 and python3.8-venv
        # Note server is bionic do upgrade from apt repository
        python3 -m venv env # this will work
        . env/bin/activate # activate virtual env
        python3 -m pip install -r requirements.txt
   # - name: Run Tests
   #   run: |
   #     python manage.py test
